{% set name = "sparsecca" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/theislab/sparsecca/archive/{{ version }}.tar.gz
  sha256: 4e0575d07c6b97663244e2de95e28eb66538d162efcc0d9d3a6c0760672a1c52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pandas
    - numpy
    - statsmodels
    - pyomo

test:
  imports:
    - sparsecca
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A full implementation of sparse CCA.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/theislab/sparsecca
  dev_url: https://github.com/theislab/sparsecca

extra:
  recipe-maintainers:
    - Zethson
    - yugeji
